token: "DO54ZFwyQk3hIZ1OvVJFyVIsV5EVuonY"
host: "0.0.0.0"   # 让外网也能访问
port: 11220    # Flask 启动端口

items:
  - type: handleprogram
    id: wechat
    process_name: "Weixin.exe"
    path: "D:/normal/Weixin/Weixin.exe"
    args: ""
    kill_all: true
    remark: "操作微信"

  - type: openfile
    id: arknights
    path: "D:/tools/MAA/MAA.exe"
    args: ""
    remark: "启动明日方舟（MAA）"

  - type: killprocess
    id: steam
    process_name: "steam.exe"
    kill_all: false
    remark: "启动Steam"

  - type: runcommand
    id: shutdown
    command: "shutdown -s -t 10"
    args: ""
    remark: "一键关机"

  - type: openlink
    id: baidu
    link: "https://www.baidu.com"
    remark: "打开百度"
